---
- hosts: localhost
  gather_facts: no
  vars:
      instance_type: t2.micro
      image: ami-0d5d9d301c853a04a
      region: us-east-2
      keypair: plotbot
      subnet: subnet-92d08ce8
      sg_group: sg-0c097f91462118199
  vars_files:
    - plotbot_vault.yml

  tasks:
    - name: Launch the new EC2 Instance
      ec2_instance:
        name: plotbot-base2
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_type: "{{instance_type}}"
        image_id: "{{image}}"
        wait: yes 
        region: "{{region}}"
        key_name: "{{keypair}}"
        vpc_subnet_id: "{{subnet}}"
        security_group: "{{sg_group}}"
        network:
          assign_public_ip: true
      register: ec2
    
    - debug:
        msg: "{{ec2}}"